// This file is generated by rust-protobuf 2.8.0. Do not edit
// @generated

// https://github.com/Manishearth/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![cfg_attr(rustfmt, rustfmt_skip)]

#![allow(box_pointers)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unsafe_code)]
#![allow(unused_imports)]
#![allow(unused_results)]
//! Generated file from `service.proto`

use protobuf::Message as Message_imported_for_functions;
use protobuf::ProtobufEnum as ProtobufEnum_imported_for_functions;

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_2_8_0;

#[derive(PartialEq,Clone,Default)]
pub struct Data {
    // message fields
    pub Payload: ::std::vec::Vec<u8>,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a Data {
    fn default() -> &'a Data {
        <Data as ::protobuf::Message>::default_instance()
    }
}

impl Data {
    pub fn new() -> Data {
        ::std::default::Default::default()
    }

    // bytes Payload = 1;


    pub fn get_Payload(&self) -> &[u8] {
        &self.Payload
    }
    pub fn clear_Payload(&mut self) {
        self.Payload.clear();
    }

    // Param is passed by value, moved
    pub fn set_Payload(&mut self, v: ::std::vec::Vec<u8>) {
        self.Payload = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_Payload(&mut self) -> &mut ::std::vec::Vec<u8> {
        &mut self.Payload
    }

    // Take field
    pub fn take_Payload(&mut self) -> ::std::vec::Vec<u8> {
        ::std::mem::replace(&mut self.Payload, ::std::vec::Vec::new())
    }
}

impl ::protobuf::Message for Data {
    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_singular_proto3_bytes_into(wire_type, is, &mut self.Payload)?;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if !self.Payload.is_empty() {
            my_size += ::protobuf::rt::bytes_size(1, &self.Payload);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream) -> ::protobuf::ProtobufResult<()> {
        if !self.Payload.is_empty() {
            os.write_bytes(1, &self.Payload)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> Data {
        Data::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static mut descriptor: ::protobuf::lazy::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ::protobuf::reflect::MessageDescriptor,
        };
        unsafe {
            descriptor.get(|| {
                let mut fields = ::std::vec::Vec::new();
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeBytes>(
                    "Payload",
                    |m: &Data| { &m.Payload },
                    |m: &mut Data| { &mut m.Payload },
                ));
                ::protobuf::reflect::MessageDescriptor::new::<Data>(
                    "Data",
                    fields,
                    file_descriptor_proto()
                )
            })
        }
    }

    fn default_instance() -> &'static Data {
        static mut instance: ::protobuf::lazy::Lazy<Data> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const Data,
        };
        unsafe {
            instance.get(Data::new)
        }
    }
}

impl ::protobuf::Clear for Data {
    fn clear(&mut self) {
        self.Payload.clear();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for Data {
    fn fmt(&self, f: &mut ::std::fmt::Formatter) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for Data {
    fn as_ref(&self) -> ::protobuf::reflect::ProtobufValueRef {
        ::protobuf::reflect::ProtobufValueRef::Message(self)
    }
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\rservice.proto\"\x20\n\x04Data\x12\x18\n\x07Payload\x18\x01\x20\x01(\
    \x0cR\x07Payload2-\n\x0bTestService\x12\x1e\n\nDataStream\x12\x05.Data\
    \x1a\x05.Data(\x010\x01B\x03\xf8\x01\x01J\xad\x02\n\x06\x12\x04\0\0\n\
    \x01\n\x08\n\x01\x0c\x12\x03\0\0\x12\n\x08\n\x01\x08\x12\x03\x02\0\x1f\n\
    \x0b\n\x04\x08\xe7\x07\0\x12\x03\x02\0\x1f\n\x0c\n\x05\x08\xe7\x07\0\x02\
    \x12\x03\x02\x07\x17\n\r\n\x06\x08\xe7\x07\0\x02\0\x12\x03\x02\x07\x17\n\
    \x0e\n\x07\x08\xe7\x07\0\x02\0\x01\x12\x03\x02\x07\x17\n\x0c\n\x05\x08\
    \xe7\x07\0\x03\x12\x03\x02\x1a\x1e\n\n\n\x02\x04\0\x12\x04\x04\0\x06\x01\
    \n\n\n\x03\x04\0\x01\x12\x03\x04\x08\x0c\n\x0b\n\x04\x04\0\x02\0\x12\x03\
    \x05\x04\x16\n\r\n\x05\x04\0\x02\0\x04\x12\x04\x05\x04\x04\x0e\n\x0c\n\
    \x05\x04\0\x02\0\x05\x12\x03\x05\x04\t\n\x0c\n\x05\x04\0\x02\0\x01\x12\
    \x03\x05\n\x11\n\x0c\n\x05\x04\0\x02\0\x03\x12\x03\x05\x14\x15\n\n\n\x02\
    \x06\0\x12\x04\x08\0\n\x01\n\n\n\x03\x06\0\x01\x12\x03\x08\x08\x13\n\x0b\
    \n\x04\x06\0\x02\0\x12\x03\t\x046\n\x0c\n\x05\x06\0\x02\0\x01\x12\x03\t\
    \x08\x12\n\x0c\n\x05\x06\0\x02\0\x05\x12\x03\t\x13\x19\n\x0c\n\x05\x06\0\
    \x02\0\x02\x12\x03\t\x1a\x1e\n\x0c\n\x05\x06\0\x02\0\x06\x12\x03\t)/\n\
    \x0c\n\x05\x06\0\x02\0\x03\x12\x03\t04b\x06proto3\
";

static mut file_descriptor_proto_lazy: ::protobuf::lazy::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::lazy::Lazy {
    lock: ::protobuf::lazy::ONCE_INIT,
    ptr: 0 as *const ::protobuf::descriptor::FileDescriptorProto,
};

fn parse_descriptor_proto() -> ::protobuf::descriptor::FileDescriptorProto {
    ::protobuf::parse_from_bytes(file_descriptor_proto_data).unwrap()
}

pub fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    unsafe {
        file_descriptor_proto_lazy.get(|| {
            parse_descriptor_proto()
        })
    }
}
